language: node_js
node_js:
  - '12'
#os: osx todo restore safari
install: ./build/npm-install.sh
script:
  - npm run deploy
after_script:
  - node ./node_modules/coveralls/bin/coveralls.js < ./reports/lcov.info
sudo: required
deploy:
  - provider: npm
    skip_cleanup: true
    email: comindware-awesome-bot@comindware.com
    api_key:
      secure: 2f2e067a-2ca1-4b13-8633-48e508c7ffd4
    on:
      tags: true
      repo: comindware/core-ui
      branch: master
  - provider: script
    script: npm run deploy:pages
    skip_cleanup: true
    on:
      tags: true
      repo: comindware/core-ui
      branch: master
addons:
  firefox: "latest"